### ISSUE TITLE
chore: declared variable is not used

### ISSUE THREAD

**Issue by namkyu1999** [litmuschaos/litmus#4386] opened 2024-01-18 07:08 UTC
This result of append is never used. @Saranya-jena added this variable. Can you take a look at this code?

https://github.com/litmuschaos/litmus/blob/399af62ca877c265160ea9edc6a2b8ee1b7f5f9d/chaoscenter/graphql/server/pkg/chaos_experiment/ops/service.go#L724-L727

**Comment by nanu1605** [comment] 2024-01-25 08:15
Hi @namkyu1999, The result of the `append` operation is never used, might be a slight possibility that the code is incomplete

**Comment by kanhaiya04** [comment] 2024-02-19 17:59
I want to work on this.

I think we have to return the `probes` in the `UpdateRuntimeCronWorkflowConfiguration` func as well.
@Saranya-jena, need your view before proceeding.

**Comment by Saranya-jena** [comment] 2024-02-27 05:02
Going on the first come basis, @prashantrewar are you still interested in working on this issue?

**Comment by prashantrewar** [comment] 2024-03-14 17:04
Hey @Saranya-jena and @kanhaiya04, I think the issue is resolved in this [PR](https://github.com/litmuschaos/litmus/pull/4366).

**Comment by namkyu1999** [comment] 2024-03-15 00:39
@prashantrewar this issue is not resolved, anyone who wants to work on this issue, please raise a pr 😄

**Comment by rootxrishabh** [comment] 2024-03-15 21:49
@namkyu1999 @Saranya-jena If possible, I can take this up!

**Comment by namkyu1999** [comment] 2024-03-16 03:25
Hey @prashantrewar , let me know if you are interested in working on this issue, if not I will assign this issue to @rootxrishabh

**Comment by namkyu1999** [comment] 2024-04-03 02:20
can you share the updates @rootxrishabh ?

**Comment by rootxrishabh** [comment] 2024-04-03 05:43
@namkyu1999 I'm unable to take on this task at the moment. My apologies. @MichaelMorrisEst has already made a PR addressing the issue. Right?

**Comment by namkyu1999** [comment] 2024-04-03 06:26
np @rootxrishabh 😄

**Closed** 2024-04-05 04:50 UTC
Labels: good first issue
