### ISSUE TITLE
Request for a test case to check litmus manifests

### ISSUE THREAD

**Issue by rajdas98** [litmuschaos/litmus#1493] opened 2020-05-08 10:27 UTC
- Request to add a new test case to check the litmus manifests and add it in circleci
- k8s-env: Minikube or KIND
- Repo- https://github.com/litmuschaos/pages

**Comment by ksatchit** [comment] 2020-07-17 05:35
This is a duplicate of https://github.com/litmuschaos/litmus/issues/213

**Closed by ksatchit** 2020-07-17 05:35 UTC
