### ISSUE TITLE
Getting unauthorized error in helper pods logs while injecting chaose,Can someone pls look into this.

### ISSUE THREAD

**Issue by rrraaa1** [litmuschaos/litmus#3271] opened 2021-10-08 01:09 UTC
kubectl logs pod-network-latency-helper-jrcdpa -n kafka

W1007 09:54:25.609564    5866 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-10-07T09:54:25Z" level=info msg="Helper Name: network-chaos"
time="2021-10-07T09:54:25Z" level=info msg="[PreReq]: Getting the ENV variables"
time="2021-10-07T09:54:25Z" level=fatal msg="helper pod failed, err: Unauthorized"

**Comment by uditgaurav** [comment] 2021-11-09 04:42
cc: @Jonsy13

**Comment by Jonsy13** [comment] 2021-11-10 18:38
Hi @rrraaa1, as we discussed over slack, I think this issue was because of psps and was resolved with the provided psps manifest. Let us know if the issue is still persisting. If resolved feel free to close this issue. Thankyou!!

**Comment by ispeakc0de** [comment] 2022-10-16 18:02
Closing this inactive issue

**Closed by ispeakc0de** 2022-10-16 18:02 UTC
