### ISSUE TITLE
Ec2 Terminate (vs stop) Experiment

### ISSUE THREAD

**Issue by nalbury** [litmuschaos/litmus#3420] opened 2022-01-10 13:19 UTC
I've noticed (and seen conversations confirming) that the current ec2 terminate by tag and terminate by id experiments only stop a running instance vs actually terminating it. 

It appears based on this [conversation](https://github.com/litmuschaos/litmus-go/pull/360) that this is intentional and not just an incorrect naming, but is there an alternative experiment that will fully terminate an instance?

We almost never stop instances, we terminate them similar to Kubernetes pods, so I was hoping for the instance equivalent of the pod-delete experiment.

Aside from the desire to fully terminate an instance as part of an experiment, this also prevents us from running the ec2 terminate experiments on spot instances which is a good portion of our fleet (and arguably the place we want to test this behavior most).

**Comment by yogeek** [comment] 2022-01-25 10:20
Totally agree !
Same issue discussed here : https://kubernetes.slack.com/archives/CNXNB0ZTN/p1641534107031500

**Comment by neelanjan00** [comment] 2022-10-12 11:45
Duplicate of https://github.com/litmuschaos/litmus-go/pull/360.

**Closed by neelanjan00** 2022-10-12 11:45 UTC
