### ISSUE TITLE
Bug chaos experiment

### ISSUE THREAD

**Issue by ilyes-ihadjadene** [litmuschaos/litmus#1513] opened 2020-05-20 12:09 UTC
**What happened**:
I am trying to apply container-kill experiement on a keycloak container.
I got a KeyError :
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'getpwuid( ): uid not found: 1000500000'
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

**What you expected to happen**:
container-kill experiement on a keycloak container

**How to reproduce it (as minimally and precisely as possible)**:
I am working on openshift environnement with :
Litmus v1.4
Openshift v4
Kubernetes v1.16.2

**Comment by ksatchit** [comment] 2020-05-20 12:10
@ilyes-ihadjadene , can you share the entire log of the container-kill experiment pod?

**Comment by ilyes-ihadjadene** [comment] 2020-05-20 12:28
@ksatchit , here are the logs of the container-kill experiment 

`ansible-playbook 2.7.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
statically imported: /experiments/generic/container_kill/container_kill_ansible_prerequisites.yml
2020-05-20 12:23:53.543594 PLAYBOOK: container_kill_ansible_logic.yml 
1 plays in ./experiments/generic/container_kill/container_kill_ansible_logic.yml
2020-05-20 12:23:53.585489 ************ BRACE YOURSELF, EXPERIMENT BEGINS! ************ 
2020-05-20 12:23:53.614237 Step: Gathering Facts 
task path: /experiments/generic/container_kill/container_kill_ansible_logic.yml:2
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'getpwuid(): uid not found: 1000500000'
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
	to retry, use: --limit @/experiments/generic/container_kill/container_kill_ansible_logic.retry
2020-05-20 12:23:53.617799 ************ RELAX, EXPERIMENT ENDS! ************ 
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1 `

**Comment by ksatchit** [comment] 2020-05-20 13:11
Seems related to this issue: https://github.com/ansible/galaxy/issues/2303

**Comment by aelbarkani** [comment] 2020-05-20 14:40
https://major.io/2019/03/22/running-ansible-in-openshift-with-arbitrary-uids/

@ksatchit if facts are not needed, would be possible to turn the gather_facts down in ansible playbooks ?

**Comment by ksatchit** [comment] 2020-05-20 15:45
Yes, that could be done! We can pass this ENV in the chaosengine ENVs: 

```
            - name: DEFAULT_GATHERING
              value: "explicit"
```

**Comment by ilyes-ihadjadene** [comment] 2020-05-25 10:23
I have added the ENV to the chaosengine, it doesn't seem to be working. I still have the same issue on the container-kill : 
[container-kill-log.txt](https://github.com/litmuschaos/litmus/files/4676699/container-kill-log.txt)

Here is the chaos-runner log : 
[chaos-runner log.txt](https://github.com/litmuschaos/litmus/files/4676564/chaos-runner.log.txt)

I checked that the ENV has been added with ` oc get po <nomducontainerkillpod> -o yaml` , which seems to be the case. 
[container-kill pod.txt](https://github.com/litmuschaos/litmus/files/4676722/container-kill.pod.txt)

I share my RBAC and Chaosengine files for more details.
[Rbac manifest.txt](https://github.com/litmuschaos/litmus/files/4676712/Rbac.manifest.txt)
[chaosengine manifest.txt](https://github.com/litmuschaos/litmus/files/4676570/chaosengine.manifest.txt)

**Comment by ksatchit** [comment] 2020-05-27 12:58
cc: @rajdas98

**Comment by aelbarkani** [comment] 2020-06-14 16:07
any update on this issue ?

**Comment by ispeakc0de** [comment] 2020-07-17 08:34
Hi @ilyes-ihadjadene 

I am suspecting the issue is due to the `container-kill-sa` service account is unable to access the uid(1000500000). Have you subscribed for the scc from this service account(`conttainer-kill-sa` ).
If not, please try the following command before applying the chaosengine manifest:
`oc adm policy add-scc-to-user anyuid system:serviceaccount:keycloak-argocd-app:container-kill-sa`

an alternate approach can be we can try the litmus-go experiments in litmus 1.6.0:
everything remains same you just have to apply the litmus-go custom resource instead of ansible one.
[litmus-go-CR](https://hub.litmuschaos.io/api/chaos/1.6.0?file=charts/generic/container-kill/experiment.yaml) and for more details please refer [pod-delete](https://docs.litmuschaos.io/docs/container-kill/)

**Comment by ispeakc0de** [comment] 2020-08-13 12:23
All the generic experiments are converted to go and updated on the [hub](https://hub.litmuschaos.io/generic). You can directly use them.

No new activity observed for a long time. I am closing this issue by assuming that the issue has been fixed. Please feel free to reopen the issue if still find any difficulty.

**Closed by ispeakc0de** 2020-08-13 12:23 UTC
Labels: kind/bug, project/community
