### ISSUE TITLE
Not able to run the experiments in default namespace

### ISSUE THREAD

**Issue by SonalJain1707** [litmuschaos/litmus#3133] opened 2021-08-16 08:32 UTC
Hi Team,

We are using litmus chaos toolkit to run experiments.
We are unable to run any experiment in the default namespace.
Error is :
Warning ChaosResourcesOperationFailed 47m (x25 over 6d19h) chaos-operator (chaos start) Unable to get chaos resources
Could you please help us at the earliest as we are completely stuck?

Thanks,
Sonal.

**Comment by prithvi1307** [comment] 2021-08-16 08:33
@SonalJain1707 would urge you to ask the same question in the slack community for quick assistance.
To join our slack please follow the following steps!
Step 1: Join the Kubernetes slack using the following link: https://slack.k8s.io/
Step 2: Join the #litmus channel on the Kubernetes slack or use this link after joining the Kubernetes slack: https://slack.litmuschaos.io/

**Comment by ispeakc0de** [comment] 2022-10-16 17:56
Closing this issue as it is not a bug.

**Closed by ispeakc0de** 2022-10-16 17:56 UTC
Labels: bug
